# ref. https://github.com/marketplace/actions/merge-pull-requests
# dependabotからのPRを即マージ
name: automerge
on:
  pull_request:
    types:
      - labeled
      - opened
      - reopened
      - unlocked
    branches:
      - "dependabot/**"
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@80acb0f883348dcfd0e526288f7d27a12b9333be"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
