name: Laravel

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]



jobs:
  laravel-tests:
    services:
      mysql:
        image: mysql:8.0.19
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_DATABASE: test

    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: test
      DB_USERNAME: root
      DB_PASSWORD: pass
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Cache directory making
      run: find config/ -type f | xargs grep storage_path | grep framework | sed -e 's/^.*storage_path//' | tr -d ",\(\)'" | awk '{ print "storage/"$0 }' | xargs mkdir -p
    - name: List files
      run: ls
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.db
    - name: Run database migrations
      run: php artisan migrate
    - name: Set executable
      run: chmod +x ./setup.sh
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: mtsql
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
